### ISSUE TITLE
Failed to add Webhook

### ISSUE THREAD

**Issue by carliandro** [sanderv32/gogs-webhook-plugin#2]
Gogs version (or commit ref): 1.5
Git version: 2.9.2
Operating system: Windows
Database (use [x]): MySQL
Can you reproduce the bug at https://try.gogs.io: Not relevant
Log gist: No valid crumb was included in the request

Hi guys,
I installed Gogs and I am trying integrate with Jenkins. I did read documentation but I don't found nothing about the integration.

Both are installed on my network.

I have installed Gogs Plugin(1.0.4) on my Jenkins server.
I create a job on jenkins configured to "see" my gogs repository. I can execute a build and the Jenkins get all sources and build them.

In Gogs I configured a Webhook pointing out for my job. But I receive the follow message: 
Problem accessing /jenkins/. 
No valid crumb was included in the request

Can you help me

**Comment by sanderv32** [comment]
Can you please use the jenkins site to reports problems? In the meantime i will remove this repo.
